### ISSUE TITLE
这个工具可以用于自己搭建的fabric网络吗？

### ISSUE THREAD

**Issue by Jalins** [yakumioto/alkaid#16]
不是使用test-network，使用步骤都一模一样吗？

**Comment by yakumioto** [comment]
目前打算是做成 BaaS Service 的, 但是进度比较缓慢. 

[v0.2.0](https://github.com/yakumioto/alkaid/tree/v0.2.0) 算是一个部署工具, 在网络启动后的部署工具.

支持的功能在 [README](https://github.com/yakumioto/alkaid/blob/v0.2.0/README-zh.md) 里有详细介绍, 可以看看.

**Comment by Jalins** [comment]
> 目前打算是做成 BaaS Service 的, 但是进度比较缓慢.
> 
> [v0.2.0](https://github.com/yakumioto/alkaid/tree/v0.2.0) 算是一个部署工具, 在网络启动后的部署工具.
> 
> 支持的功能在 [README](https://github.com/yakumioto/alkaid/blob/v0.2.0/README-zh.md) 里有详细介绍, 可以看看.

我的理解你这个工具是将相同的操作抽离出来，变量由用户自行去填入，我现在是搭建自己的网络，可以使用你的这个工具来操作我的网络吧？

**Comment by yakumioto** [comment]
对的～

jalins <notifications@github.com> 于 2020年3月30日周一 17:10写道：
